[settings]
python.uv_venv_auto = true

[env]
# Use the project name derived from the current directory
PROJECT_NAME = "{{ config_root | basename }}"

# Automatic virtualenv activation
_.python.venv = { path = ".venv", create = true }

# Set up the path for node module binaries
BIN_PATH = "{{ config_root }}/node_modules/.bin"

[tools]
node = "lts"
python = "3.12"
ruby = "3.2.3"
uv = "latest"

[tasks."uv:pip:install"]
description = "Install python dependencies"
run = "uv pip install -r requirements.txt"

[tasks."bundle:install"]
description = "Install gem dependencies"
run = "bundle install"

[tasks."pre-commit:run:-all-files"]
run = "pre-commit run --all-files"
